export const getMockedJokes = () => {
  return {
    '27/11/2022': {
      category: 'Dark',
      delivery: 'The other 2 though, are hilarious!',
      error: false,
      flags: {
        explicit: false,
        nsfw: false,
        political: true,
        racist: false,
        religious: false,
        sexist: false,
      },
      id: 79,
      isLiked: false,
      lang: 'en',
      safe: false,
      setup: '9/11 jokes are not funny.',
      type: 'twopart',
    },
    '26/11/2022': {
      category: 'Dark',
      delivery: 'Thankfully he was still chained up in my basement.',
      error: false,
      flags: {
        explicit: false,
        nsfw: false,
        political: true,
        racist: false,
        religious: false,
        sexist: false,
      },
      id: 78,
      liked: true,
      lang: 'en',
      safe: false,
      setup:
        'I was walking down the street and saw some black guy on a bike and it looked just like mine so I ran home to check.',
      type: 'twopart',
    },
    '25/11/2022': {
      category: 'Dark',
      setup: 'Why should you never talk to pi?',
      delivery: 'Because it will go on forever.',
      error: false,
      flags: {
        explicit: false,
        nsfw: false,
        political: true,
        racist: false,
        religious: false,
        sexist: false,
      },
      id: 77,
      liked: false,
      lang: 'en',
      safe: false,
      type: 'twopart',
    },
    '24/11/2022': {
      error: false,
      category: 'Dark',
      type: 'twopart',
      setup: "What's the difference between a jew and a pizza?",
      delivery: "The pizza doesn't scream when you put it in the oven.",
      flags: {
        nsfw: false,
        religious: false,
        political: false,
        racist: true,
        sexist: false,
        explicit: true,
      },
      liked: false,
      id: 128,
      safe: false,
      lang: 'en',
    },
    '23/11/2022': {
      error: false,
      category: 'Programming',
      type: 'twopart',
      setup: "What do you call a developer who doesn't comment code?",
      delivery: 'A developer.',
      flags: {
        nsfw: false,
        religious: false,
        political: false,
        racist: false,
        sexist: false,
        explicit: false,
      },
      liked: true,
      id: 14,
      safe: true,
      lang: 'en',
    },
  };
};
